title: Saman Saadi
author:
  name: Saman Saadi
  email: ''
metadata:
    description: 'Welcome to Saman Saadi Website'
blog:
    hero_image: 'user://pages/files/images/my-header.jpg'
    
taxonomies: [category,en_tag, fa_tag]

#menu:
#    - text: Blog
#      icon: pencil
#      url: /blog
#      class: external
#    - icon: linkedin
#      url: https://www.linkedin.com/in/samansaadi/
#      class: external


